### PR TITLE
Manuals and specifications

### PR DESCRIPTION
**Pull request by bugron**

### CODE REVIEW

**Comment by bugron** [comment]
Didn't come up with an appropriate translation for the term "specification"... any ideas @javascript-tutorial/translate-hy ?

**Review by ArthurHakobyan — CHANGES_REQUESTED** [review]
you can change the name specification to " տարբերակ " but leave the English word in parentheses

**Comment by bugron** [comment]
@ArthurHakobyan I decided to go with the 'բնութագիր՛ option as Microsoft Terminology Search suggested it.

**Review by ArthurHakobyan — APPROVED** [review]

**Review by ArthurHakobyan — APPROVED** [review]

**Pull request merged**
