### PR TITLE
Function expressions

### PR DESCRIPTION
**Pull request by galenteryan**
Done

### CODE REVIEW

**Comment by galenteryan** [comment]
Is there any problem?

**Comment by iliakan** [comment]
@ArthurHakobyan, @bugron, @vhgn, is anyone active? ;)

**Comment by iliakan** [comment]
Բարի երեկո, @galenteryan!

Do you have enough experience with JS? 

If you do, please accept the invitation to become a maintainer and be able to merge PRs.

**Comment by galenteryan** [comment]
Ողջույն @iliakan!

Yes, I have.

I've accepted the invitation, thank you.

**Comment by bugron** [comment]
Hi there, sorry for my late response. As you might've already guessed I'm currently swamped with some of my business so I won't be able to participate in discussions and review translations that much nowadays. That being said I'm optimistic about what's the future and I'll try to make more time for this project.

@galenteryan welcome to the team ✨ 🚀 If you need any help don't hesitate to contact me. I promise to do my best to get back to you in a reasonable time:)

**Pull request merged**
